# Generated by Django 4.1 on 2022-09-05 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(max_length=100000, verbose_name='Content')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created date')),
                ('files', models.FileField(blank=True, null=True, upload_to='', verbose_name='File')),
            ],
        ),
    ]
