# Generated by Django 4.1 on 2022-09-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_004_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
    ]
