# Generated by Django 4.1 on 2022-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_004_blog', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='File'),
        ),
    ]
